name: Unit Test in Front End

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/frontend_unittest.yml'
    - 'src/frontend/**'
    - 'conf/**'

jobs:
  unit_tests:
    name: Unit Test
    runs-on: ubuntu-release
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Source
      run: npm build ...

    - name: Run Test
      run: npm run test ...

    - name: Test Summary
      run: codecov 
