name: Unit Test in Front End

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/frontend_unittest.yml'
    - 'src/frontend/**'
    - 'conf/**'

jobs:
  unit_tests:
    name: Unit Test
    runs-on: ubuntu-release
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Source
      uses: npm build ...

    - name: Run Test
      run: npm run test ...

    - name: Test Summary
      run: codecov

    - name: Submodule package check
      run: |
        python setup.py bdist_wheel --denas && twine check dist/e2eAIOK_denas-*.*.*-py3-none-any.whl && rm -rf build && rm -rf dist
        python setup.py bdist_wheel --sda && twine check dist/e2eAIOK_sda-*.*.*-py3-none-any.whl && rm -rf build && rm -rf dist 
